/**
 * The Candid Duo — CMS backend worker (Cloudflare Workers)
 * ---------------------------------------------------------
 * This tiny free service does several things for the hand-built CMS at /admin:
 *   1. Logs you in with your GitHub account (unchanged since the Decap days).
 *   2. Proxies "Generate with AI" story requests to the Gemini API.
 *   3. Proxies "Fetch details from URL" product-link lookups (also via
 *      Gemini) — fetching arbitrary product pages and extracting the image
 *      must happen server-side anyway (the browser can't do either due to
 *      CORS), so it rides the same Gemini key as AI stories.
 *   4. Proxies "pull latest YouTube video" and "add TikTok video from URL"
 *      lookups for the homepage's Watch & Listen section — both hit public,
 *      free endpoints (YouTube's channel RSS feed, TikTok's oEmbed API), no
 *      API key or cost involved, just server-side fetches the browser can't
 *      make itself due to CORS.
 *   5. Counts page views for the CMS Dashboard (a tiny, cookie-free, first-party
 *      traffic counter — see "Traffic counter" below). It needs a free D1
 *      database bound to this worker as `DB` (SETUP-GUIDE.md, Step 6g); every
 *      other feature works without it.
 * The two AI features keep your API key server-side instead of in the
 * browser's JS where anyone could read it. Gemini was picked for these two
 * specifically because Google AI Studio's free tier needs no credit card —
 * unlike most other providers, this stays $0 for normal personal-blog use.
 * You do NOT edit this file's logic. Just copy ALL of it into the Cloudflare
 * Worker editor, then set the secrets below. Step-by-step instructions are
 * in SETUP-GUIDE.md (Step 6 for login, Step 6f for the AI features).
 *
 * Secrets to set in the Cloudflare dashboard (Settings → Variables and Secrets):
 *   GITHUB_CLIENT_ID      — from your GitHub OAuth App (Step 6b)
 *   GITHUB_CLIENT_SECRET  — from your GitHub OAuth App (Step 6b)
 *   GITHUB_REPO           — "YOURNAME/YOURNAME.github.io" — required for the
 *                           AI features, so only someone with push access to
 *                           *this* repo can trigger them
 *   GEMINI_API_KEY        — free, from aistudio.google.com/apikey — required
 *                           for the AI features only; login works without it
 *   SITE_ORIGIN           — optional. Only page views reported from this origin
 *                           are counted. Defaults to https://thecandidduo.github.io
 *
 * Binding (Settings → Bindings → Add → D1 database):
 *   DB                    — a free D1 database for the traffic counter
 */

const AI_MODEL = "gemini-3.6-flash";
const MAX_AI_IMAGES = 6;
const MAX_AI_DOCUMENTS = 3;
const MAX_FETCHED_IMAGE_BYTES = 8 * 1024 * 1024;

const CORS_HEADERS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "GET, POST, OPTIONS",
  "access-control-allow-headers": "content-type, authorization",
};

// Both AI routes below count against the site owner's Gemini free-tier quota,
// so they require a real GitHub session with push access to *this* repo —
// otherwise anyone who found this worker's URL could burn through that quota
// with a throwaway GitHub account.
//
// `ai: false` skips the Gemini-key check for routes (like /stats) that don't call Gemini.
async function requirePushAccess(request, env, { ai = true } = {}) {
  if (ai && !env.GEMINI_API_KEY) return { ok: false, status: 500, message: "Missing GEMINI_API_KEY secret" };
  if (!env.GITHUB_REPO) return { ok: false, status: 500, message: "Missing GITHUB_REPO secret" };

  const authHeader = request.headers.get("authorization") || "";
  const githubToken = authHeader.replace(/^Bearer\s+/i, "");
  if (!githubToken) return { ok: false, status: 401, message: "Missing GitHub session" };

  const repoRes = await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}`, {
    headers: {
      authorization: `Bearer ${githubToken}`,
      "user-agent": "candidduo-cms-ai-worker",
      accept: "application/vnd.github+json",
    },
  });
  if (!repoRes.ok) return { ok: false, status: 401, message: "Invalid GitHub session" };
  const repoData = await repoRes.json();
  if (!repoData.permissions || !repoData.permissions.push)
    return { ok: false, status: 403, message: "Not authorized for this site" };
  return { ok: true };
}

function decodeXmlEntities(str) {
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function guessPlatform(hostname) {
  const h = (hostname || "").toLowerCase();
  if (h.includes("shopee")) return "Shopee";
  if (h.includes("amazon") || h.includes("amzn")) return "Amazon";
  if (h.includes("lazada")) return "Lazada";
  if (h.includes("tiktok")) return "TikTok Shop";
  if (h.includes("etsy")) return "Etsy";
  return "Other";
}

const PRODUCT_SYSTEM_PROMPT =
  "You extract product info from an e-commerce page's raw HTML for a travel " +
  "and family blog's affiliate product CMS. Look at meta tags (og:title, og:image, " +
  'og:description, product:price:amount), JSON-LD <script type="application/ld+json"> ' +
  "Product schema, and any visible price/title text in the HTML. If the page " +
  'is a bot-block / CAPTCHA / "enable JavaScript" placeholder with no real ' +
  "product info, return empty strings for fields you can't find rather than " +
  "guessing. Respond with JSON matching the given schema only.";

// Gemini's structured-output schema format (note: uppercase type names —
// this is Google's own Schema type, not standard JSON Schema).
const PRODUCT_RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    name: { type: "STRING", description: "Product name/title. Empty string if not found." },
    price: { type: "STRING", description: "Price with currency as shown on the page, e.g. 'SGD 45.90'. Empty string if not found." },
    blurb: { type: "STRING", description: "One short sentence describing the product. Empty string if not found." },
    category: { type: "STRING", description: "A short category guess, e.g. 'Camera Gear', 'Travel Essentials', 'Kids & Baby', 'Family Travel Gear'. Empty string if unsure." },
    image_url: { type: "STRING", description: "Best absolute product photo URL found (from og:image or similar). Empty string if not found." },
  },
  required: ["name", "price", "blurb", "category", "image_url"],
};

// Keep both lists in step with the "section" and "category" options in
// admin/js/schema.js — the CMS ignores any value that isn't one of its options.
const SECTION_LIST = ["Travel", "Family"];
const CATEGORY_LIST = ["Culture", "Adventure", "Guide", "Food", "Reflection", "Parenting", "Kids' Activities", "Milestones"];

const AI_SYSTEM_PROMPT =
  'You are a writer for "The Candid Duo," a warm, first-person blog by a ' +
  "couple living in Singapore about travel and family life: honest, " +
  "practical, occasionally funny stories about their trips, parenting and " +
  "everyday life at home. Given a prompt from the site admin (and any " +
  "attached photos, PDFs, or notes), write a complete blog post in that " +
  "voice: personal, vivid, specific — real place names, food, small moments " +
  "— never generic listicle copy. Keep paragraphs short. Write the body in " +
  "Markdown. Respond with JSON matching the given schema only.";

const STORY_RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    title: { type: "STRING", description: "Story title, under ~70 characters." },
    dek: { type: "STRING", description: "One italic subtitle line shown under the title." },
    excerpt: { type: "STRING", description: "1-2 sentence summary shown on cards and in search results." },
    tags: { type: "ARRAY", items: { type: "STRING" }, description: "3-6 short topical tags." },
    body: { type: "STRING", description: "Full story body in Markdown, several paragraphs." },
    section: {
      type: "ARRAY",
      items: { type: "STRING" },
      description: `Which part of the blog the story belongs to, from exactly: ${SECTION_LIST.join(", ")}. Use both for a trip with the kids.`,
    },
    category: { type: "STRING", description: `The one best fit, written exactly as one of: ${CATEGORY_LIST.join(", ")}.` },
  },
  required: ["title", "dek", "excerpt", "tags", "body", "section", "category"],
};

// Calls Gemini's generateContent endpoint with structured-output enabled and
// returns the already-parsed JSON object, or throws with a message safe to
// show the CMS user.
async function callGemini(env, { systemPrompt, parts, schema }) {
  const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${AI_MODEL}:generateContent`, {
    method: "POST",
    headers: { "content-type": "application/json", "x-goog-api-key": env.GEMINI_API_KEY },
    body: JSON.stringify({
      contents: [{ role: "user", parts }],
      systemInstruction: { parts: [{ text: systemPrompt }] },
      generationConfig: { responseMimeType: "application/json", responseSchema: schema },
    }),
  });
  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error("AI request failed: " + errText);
  }
  const result = await res.json();
  const textPart = (result.candidates?.[0]?.content?.parts || []).find((p) => p.text)?.text;
  if (!textPart) throw new Error("AI did not return a structured result");
  try {
    return JSON.parse(textPart);
  } catch {
    throw new Error("AI returned invalid JSON");
  }
}

// ---------------------------------------------------------------------------
// Traffic counter (the CMS Dashboard's "rough traffic")
// ---------------------------------------------------------------------------
// A deliberately small, privacy-friendly page-view counter that stores its
// numbers in your own Cloudflare D1 database — no cookies, no third-party
// script, no IP addresses saved. Each page view adds one to a daily tally
// keyed by page, referring site, country (from Cloudflare) and device type.
// "Unique visitors" are approximated per day from a one-way hash of
// IP + browser + a random salt that changes daily; those hashes (and the salts)
// are deleted after a day, so a visitor can't be recognised across days.
//   POST /hit    public; called by a tiny script on every page (sendBeacon)
//   GET  /stats  CMS only (needs a GitHub session with push access)
// Counts are rough by nature: ad blockers and privacy browsers hide some visitors.

const STATS_TZ_OFFSET_MIN = 8 * 60; // days roll over at midnight Singapore time
const DEFAULT_SITE_ORIGIN = "https://thecandidduo.github.io";
const BOT_RE = /bot|crawl|spider|slurp|preview|facebookexternalhit|headless|lighthouse|pingdom|uptime|monitor|curl|wget|python|httpclient|axios|node-fetch|go-http|java\//i;

const STATS_DDL = [
  "CREATE TABLE IF NOT EXISTS hits (day TEXT NOT NULL, path TEXT NOT NULL, ref TEXT NOT NULL, country TEXT NOT NULL, device TEXT NOT NULL, views INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (day, path, ref, country, device))",
  "CREATE TABLE IF NOT EXISTS uniques (day TEXT PRIMARY KEY, visitors INTEGER NOT NULL DEFAULT 0)",
  "CREATE TABLE IF NOT EXISTS seen (day TEXT NOT NULL, hash TEXT NOT NULL, PRIMARY KEY (day, hash))",
  "CREATE TABLE IF NOT EXISTS salts (day TEXT PRIMARY KEY, salt TEXT NOT NULL)",
];

let statsTablesReady = false;
async function ensureStatsTables(db) {
  if (statsTablesReady) return;
  await db.batch(STATS_DDL.map((sql) => db.prepare(sql)));
  statsTablesReady = true;
}

// Run `fn` with the tables in place. The tables are created on first use, so there's
// no SQL to paste anywhere; if the database is ever swapped for a fresh one while this
// worker is still warm, "no such table" triggers a re-create and one retry.
async function withStatsTables(db, fn) {
  await ensureStatsTables(db);
  try {
    return await fn();
  } catch (e) {
    if (!/no such table/i.test(String((e && e.message) || e))) throw e;
    statsTablesReady = false;
    await ensureStatsTables(db);
    return await fn();
  }
}

// "YYYY-MM-DD" in the site's timezone, `offsetDays` from today.
function statsDay(offsetDays = 0, now = Date.now()) {
  return new Date(now + STATS_TZ_OFFSET_MIN * 60000 + offsetDays * 86400000).toISOString().slice(0, 10);
}

function cleanPath(p) {
  if (typeof p !== "string") return "";
  const path = p.split(/[?#]/)[0].replace(/index\.html$/, "");
  return path.length <= 200 && /^\/[A-Za-z0-9\-._~%\/+]*$/.test(path) ? path : "";
}

function cleanRef(r) {
  if (typeof r !== "string") return "";
  const host = r.trim().toLowerCase().replace(/^www\./, "");
  return host.includes(".") && /^[a-z0-9.-]{3,80}$/.test(host) ? host : "";
}

function deviceFrom(ua) {
  if (/iPad|Tablet/i.test(ua)) return "tablet";
  if (/Mobi|Android|iPhone|iPod/i.test(ua)) return "mobile";
  return "desktop";
}

let saltCache = { day: "", salt: "" };
async function saltForDay(db, day, now) {
  if (saltCache.day === day) return saltCache.salt;
  let row = await db.prepare("SELECT salt FROM salts WHERE day = ?").bind(day).first();
  if (!row) {
    // First visit of a new day: create today's salt and forget anything older than yesterday.
    const cutoff = statsDay(-1, now);
    await db.batch([
      db.prepare("INSERT OR IGNORE INTO salts (day, salt) VALUES (?, ?)").bind(day, crypto.randomUUID()),
      db.prepare("DELETE FROM seen WHERE day < ?").bind(cutoff),
      db.prepare("DELETE FROM salts WHERE day < ?").bind(cutoff),
    ]);
    row = await db.prepare("SELECT salt FROM salts WHERE day = ?").bind(day).first();
  }
  saltCache = { day, salt: row.salt };
  return row.salt;
}

async function anonymousId(salt, ip, ua) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(`${salt}|${ip}|${ua}`));
  return [...new Uint8Array(digest)].slice(0, 12).map((b) => b.toString(16).padStart(2, "0")).join("");
}

// Returns a short reason string (handy for tests); the caller ignores it.
async function recordHit(request, env, now = Date.now()) {
  if (!env.DB) return "no-database";
  if ((request.headers.get("origin") || "") !== (env.SITE_ORIGIN || DEFAULT_SITE_ORIGIN)) return "wrong-origin";
  const ua = request.headers.get("user-agent") || "";
  if (!ua || BOT_RE.test(ua)) return "bot";

  let data;
  try {
    data = JSON.parse(await request.text()); // sendBeacon posts text/plain to avoid a CORS preflight
  } catch {
    return "bad-body";
  }
  const path = cleanPath(data && data.p);
  if (!path) return "bad-path";
  const ref = cleanRef(data.r);
  const country = String((request.cf && request.cf.country) || "").toUpperCase();
  const device = deviceFrom(ua);
  const day = statsDay(0, now);

  return withStatsTables(env.DB, async () => {
    const salt = await saltForDay(env.DB, day, now);
    const id = await anonymousId(salt, request.headers.get("cf-connecting-ip") || "", ua);
    const [, seen] = await env.DB.batch([
      env.DB.prepare(
        "INSERT INTO hits (day, path, ref, country, device, views) VALUES (?, ?, ?, ?, ?, 1) ON CONFLICT (day, path, ref, country, device) DO UPDATE SET views = views + 1"
      ).bind(day, path, ref, /^[A-Z]{2}$/.test(country) ? country : "", device),
      env.DB.prepare("INSERT OR IGNORE INTO seen (day, hash) VALUES (?, ?)").bind(day, id),
    ]);
    if (seen.meta && seen.meta.changes > 0) {
      await env.DB.prepare(
        "INSERT INTO uniques (day, visitors) VALUES (?, 1) ON CONFLICT (day) DO UPDATE SET visitors = visitors + 1"
      ).bind(day).run();
    }
    return "counted";
  });
}

async function buildStats(db, days, now = Date.now()) {
  return withStatsTables(db, () => queryStats(db, days, now));
}

async function queryStats(db, days, now) {
  const since = statsDay(-(days - 1), now);
  const prevSince = statsDay(-(2 * days - 1), now);
  const prevEnd = statsDay(-days, now);
  const top = (col, limit) =>
    db.prepare(`SELECT ${col} AS name, SUM(views) AS views FROM hits WHERE day >= ? GROUP BY ${col} ORDER BY views DESC LIMIT ${limit}`).bind(since);
  const [daily, uniq, pages, refs, countries, devices, prevViews, prevUniq, first] = await db.batch([
    db.prepare("SELECT day, SUM(views) AS views FROM hits WHERE day >= ? GROUP BY day").bind(since),
    db.prepare("SELECT day, visitors FROM uniques WHERE day >= ?").bind(since),
    top("path", 10),
    top("ref", 10),
    top("country", 10),
    top("device", 5),
    db.prepare("SELECT COALESCE(SUM(views), 0) AS n FROM hits WHERE day >= ? AND day <= ?").bind(prevSince, prevEnd),
    db.prepare("SELECT COALESCE(SUM(visitors), 0) AS n FROM uniques WHERE day >= ? AND day <= ?").bind(prevSince, prevEnd),
    db.prepare("SELECT MIN(day) AS day FROM hits"),
  ]);

  const viewsByDay = Object.fromEntries(daily.results.map((r) => [r.day, r.views]));
  const visitorsByDay = Object.fromEntries(uniq.results.map((r) => [r.day, r.visitors]));
  const series = [];
  for (let i = days - 1; i >= 0; i--) {
    const day = statsDay(-i, now);
    series.push({ day, views: viewsByDay[day] || 0, visitors: visitorsByDay[day] || 0 });
  }
  const list = (res) => res.results.map((r) => ({ name: r.name, views: r.views }));
  return {
    ok: true,
    timezone: "Asia/Singapore",
    days,
    since,
    firstDay: (first.results[0] && first.results[0].day) || null,
    totals: {
      views: series.reduce((n, d) => n + d.views, 0),
      visitors: series.reduce((n, d) => n + d.visitors, 0),
    },
    previous: { views: prevViews.results[0].n, visitors: prevUniq.results[0].n },
    daily: series,
    pages: list(pages),
    referrers: list(refs),
    countries: list(countries),
    devices: list(devices),
  };
}

function jsonResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS_HEADERS, "content-type": "application/json; charset=utf-8", "cache-control": "no-store" },
  });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const { pathname, searchParams } = url;
    const origin = url.origin;
    const CLIENT_ID = env.GITHUB_CLIENT_ID;
    const CLIENT_SECRET = env.GITHUB_CLIENT_SECRET;

    // Health check
    if (pathname === "/") {
      return new Response("The Candid Duo — CMS auth worker is running ✓", {
        headers: { "content-type": "text/plain; charset=utf-8" },
      });
    }

    // Page-view beacon from the public site (see "Traffic counter" above). Always
    // answers 204 straight away and counts in the background, so it can never slow
    // a page down or show a visitor an error.
    if (pathname === "/hit") {
      const work = recordHit(request, env).catch(() => {});
      if (ctx && ctx.waitUntil) ctx.waitUntil(work);
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    // Dashboard numbers — CMS only.
    if (pathname === "/stats") {
      if (request.method === "OPTIONS") return new Response(null, { headers: CORS_HEADERS });
      if (request.method !== "GET") return new Response("Method not allowed", { status: 405, headers: CORS_HEADERS });
      const access = await requirePushAccess(request, env, { ai: false });
      if (!access.ok)
        return jsonResponse({ error: access.status === 500 ? "missing_secret" : "unauthorized", message: access.message }, access.status);
      if (!env.DB)
        return jsonResponse({ error: "no_database", message: "No D1 database is bound to this worker as DB yet." }, 501);
      const days = Math.min(365, Math.max(1, parseInt(searchParams.get("days") || "30", 10) || 30));
      try {
        return jsonResponse(await buildStats(env.DB, days));
      } catch (e) {
        return jsonResponse({ error: "stats_failed", message: e.message || "Couldn't read the stats." }, 500);
      }
    }

    // AI story generation — called via fetch() from the CMS, so (unlike the
    // popup-based /auth and /callback above) it needs real CORS handling.
    if (pathname === "/generate-story") {
      const corsHeaders = CORS_HEADERS;
      if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
      if (request.method !== "POST")
        return new Response("Method not allowed", { status: 405, headers: corsHeaders });

      const access = await requirePushAccess(request, env);
      if (!access.ok) return new Response(access.message, { status: access.status, headers: corsHeaders });

      let body;
      try {
        body = await request.json();
      } catch {
        return new Response("Invalid JSON body", { status: 400, headers: corsHeaders });
      }
      const { prompt, images = [], documents = [], notes = [] } = body || {};
      if (!prompt || typeof prompt !== "string")
        return new Response("Missing prompt", { status: 400, headers: corsHeaders });
      if (images.length > MAX_AI_IMAGES)
        return new Response(`Too many images (max ${MAX_AI_IMAGES})`, { status: 400, headers: corsHeaders });
      if (documents.length > MAX_AI_DOCUMENTS)
        return new Response(`Too many documents (max ${MAX_AI_DOCUMENTS})`, { status: 400, headers: corsHeaders });

      const parts = [];
      for (const img of images) {
        if (!img || !img.data) continue;
        parts.push({ inline_data: { mime_type: img.mediaType || "image/jpeg", data: img.data } });
      }
      for (const doc of documents) {
        if (!doc || !doc.data) continue;
        parts.push({ inline_data: { mime_type: "application/pdf", data: doc.data } });
      }
      for (const note of notes) {
        if (!note || !note.text) continue;
        parts.push({ text: `Reference file "${note.name || "notes"}":\n${note.text}` });
      }
      parts.push({ text: prompt });

      let story;
      try {
        story = await callGemini(env, { systemPrompt: AI_SYSTEM_PROMPT, parts, schema: STORY_RESPONSE_SCHEMA });
      } catch (e) {
        return new Response(e.message, { status: 502, headers: corsHeaders });
      }

      return new Response(JSON.stringify(story), {
        headers: { ...corsHeaders, "content-type": "application/json" },
      });
    }

    // "Fetch details from URL" on the Products editor — fetches the product
    // page server-side (the browser can't, due to CORS), asks Gemini to
    // pull out name/price/blurb/category/image from the raw HTML, and
    // best-effort downloads the image too so it can be re-uploaded to the
    // repo like any other CMS image instead of hot-linking someone else's URL.
    if (pathname === "/fetch-product") {
      const corsHeaders = CORS_HEADERS;
      if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
      if (request.method !== "POST")
        return new Response("Method not allowed", { status: 405, headers: corsHeaders });

      const access = await requirePushAccess(request, env);
      if (!access.ok) return new Response(access.message, { status: access.status, headers: corsHeaders });

      let body;
      try {
        body = await request.json();
      } catch {
        return new Response("Invalid JSON body", { status: 400, headers: corsHeaders });
      }
      const productUrl = (body && body.url ? String(body.url) : "").trim();
      if (!productUrl) return new Response("Missing url", { status: 400, headers: corsHeaders });
      let parsed;
      try {
        parsed = new URL(productUrl);
      } catch {
        return new Response("That doesn't look like a valid URL", { status: 400, headers: corsHeaders });
      }
      if (parsed.protocol !== "http:" && parsed.protocol !== "https:")
        return new Response("That doesn't look like a valid URL", { status: 400, headers: corsHeaders });

      const platform = guessPlatform(parsed.hostname);
      const browserHeaders = {
        "user-agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
      };

      let html = "";
      try {
        const pageRes = await fetch(productUrl, {
          headers: { ...browserHeaders, accept: "text/html,application/xhtml+xml" },
          redirect: "follow",
        });
        if (pageRes.ok) html = (await pageRes.text()).slice(0, 120000);
      } catch {
        // Best-effort: some sites block server-side fetches entirely. Fall
        // through with an empty page and let the client know nothing came back.
      }

      let extracted = null;
      if (html) {
        try {
          extracted = await callGemini(env, {
            systemPrompt: PRODUCT_SYSTEM_PROMPT,
            parts: [{ text: `Page URL: ${productUrl}\n\nPage HTML (truncated):\n${html}` }],
            schema: PRODUCT_RESPONSE_SCHEMA,
          });
        } catch {
          // Leave extracted as null; the client still gets the platform guess.
        }
      }

      let image = null;
      if (extracted && extracted.image_url) {
        try {
          const imgRes = await fetch(extracted.image_url, { headers: browserHeaders });
          if (imgRes.ok) {
            const buf = await imgRes.arrayBuffer();
            if (buf.byteLength > 0 && buf.byteLength <= MAX_FETCHED_IMAGE_BYTES) {
              const bytes = new Uint8Array(buf);
              let binary = "";
              for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
              image = { data: btoa(binary), mediaType: imgRes.headers.get("content-type") || "image/jpeg" };
            }
          }
        } catch {
          // Fall back to returning just the image URL below.
        }
      }

      return new Response(
        JSON.stringify({
          platform,
          name: extracted?.name || "",
          price: extracted?.price || "",
          blurb: extracted?.blurb || "",
          category: extracted?.category || "",
          imageUrl: extracted?.image_url || "",
          image,
          pageFetched: Boolean(html),
        }),
        { headers: { ...corsHeaders, "content-type": "application/json" } }
      );
    }

    // "Pull latest YouTube video" on the Homepage editor's Watch & Listen
    // tab. Every channel has a free, public Atom feed — no API key, no
    // cost — but the browser can't fetch it directly (no CORS), and can't
    // resolve a "@handle" URL to the channel ID the feed needs either.
    if (pathname === "/latest-youtube") {
      const corsHeaders = CORS_HEADERS;
      if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
      if (request.method !== "GET") return new Response("Method not allowed", { status: 405, headers: corsHeaders });

      const channelUrl = searchParams.get("channel");
      if (!channelUrl) return new Response("Missing ?channel=", { status: 400, headers: corsHeaders });

      const browserHeaders = {
        "user-agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
      };

      try {
        const pageRes = await fetch(channelUrl, { headers: browserHeaders });
        if (!pageRes.ok) throw new Error("Couldn't load that YouTube channel page.");
        const html = await pageRes.text();
        // YouTube has changed the exact embedded-JSON field name behind this
        // before, so try the canonical link tag first — a much more stable
        // signal — before falling back to the JSON key.
        const channelIdMatch =
          html.match(/<link rel="canonical" href="https:\/\/www\.youtube\.com\/channel\/(UC[\w-]{22})"/) ||
          html.match(/"externalId":"(UC[\w-]{22})"/) ||
          html.match(/"channelId":"(UC[\w-]{22})"/);
        if (!channelIdMatch) throw new Error("Couldn't find a channel ID on that page.");

        const feedRes = await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${channelIdMatch[1]}`, {
          headers: browserHeaders,
        });
        // YouTube 404s this feed for a channel with zero public uploads,
        // rather than returning an empty (but valid) feed.
        if (feedRes.status === 404) throw new Error("This channel doesn't have any public videos yet.");
        if (!feedRes.ok) throw new Error("Couldn't load this channel's video feed.");
        const xml = await feedRes.text();
        const entry = xml.split("<entry>")[1];
        if (!entry) throw new Error("This channel doesn't have any videos yet.");
        const videoId = (entry.match(/<yt:videoId>([\w-]+)<\/yt:videoId>/) || [])[1];
        const title = (entry.match(/<title>([\s\S]*?)<\/title>/) || [])[1];
        if (!videoId) throw new Error("Couldn't read a video ID from the feed.");

        return new Response(
          JSON.stringify({
            videoId,
            title: decodeXmlEntities(title || ""),
            thumbnail: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
            url: `https://www.youtube.com/watch?v=${videoId}`,
          }),
          { headers: { ...corsHeaders, "content-type": "application/json" } }
        );
      } catch (e) {
        return new Response(e.message || "Couldn't fetch the latest video.", { status: 502, headers: corsHeaders });
      }
    }

    // "Add TikTok video from URL" on the same tab. TikTok has no equivalent
    // public feed to auto-discover a channel's latest video (that needs
    // their developer API and an approval process), but a known video's
    // metadata is available from their public oEmbed endpoint — the same
    // one any website uses to embed a TikTok video, no key required.
    if (pathname === "/tiktok-oembed") {
      const corsHeaders = CORS_HEADERS;
      if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
      if (request.method !== "GET") return new Response("Method not allowed", { status: 405, headers: corsHeaders });

      const videoUrl = searchParams.get("url");
      if (!videoUrl) return new Response("Missing ?url=", { status: 400, headers: corsHeaders });

      try {
        const oembedRes = await fetch(`https://www.tiktok.com/oembed?url=${encodeURIComponent(videoUrl)}`);
        if (!oembedRes.ok) throw new Error("Couldn't find that TikTok video — check the link.");
        const data = await oembedRes.json();
        if (data.embed_type && data.embed_type !== "video")
          throw new Error("That looks like a profile link, not a specific video — paste the link to one TikTok video instead.");
        const idMatch = videoUrl.match(/video\/(\d+)/);
        const videoId = idMatch ? idMatch[1] : data.embed_product_id || "";
        if (!videoId) throw new Error("Couldn't read a video ID from that link.");

        return new Response(
          JSON.stringify({
            videoId,
            title: data.title || "",
            authorName: data.author_name || "",
            // Signed and short-lived (has an x-expires param) — fine to show
            // once, but the CMS must not persist this into saved content.
            thumbnail: data.thumbnail_url || "",
            url: videoUrl,
          }),
          { headers: { ...corsHeaders, "content-type": "application/json" } }
        );
      } catch (e) {
        return new Response(e.message || "Couldn't fetch that TikTok video.", { status: 502, headers: corsHeaders });
      }
    }

    // 1) Kick off GitHub login
    if (pathname === "/auth") {
      if (!CLIENT_ID) return new Response("Missing GITHUB_CLIENT_ID secret", { status: 500 });
      const gh = new URL("https://github.com/login/oauth/authorize");
      gh.searchParams.set("client_id", CLIENT_ID);
      gh.searchParams.set("redirect_uri", `${origin}/callback`);
      gh.searchParams.set("scope", searchParams.get("scope") || "repo,user");
      gh.searchParams.set("state", crypto.randomUUID());
      return Response.redirect(gh.toString(), 302);
    }

    // 2) GitHub sends the user back here with a code
    if (pathname === "/callback") {
      const code = searchParams.get("code");
      if (!code) return new Response("Missing ?code", { status: 400 });
      if (!CLIENT_ID || !CLIENT_SECRET)
        return new Response("Missing GitHub client secrets", { status: 500 });

      const tokenRes = await fetch("https://github.com/login/oauth/access_token", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json",
          "user-agent": "decap-cms-oauth-worker",
        },
        body: JSON.stringify({ client_id: CLIENT_ID, client_secret: CLIENT_SECRET, code }),
      });
      const data = await tokenRes.json();

      if (data.error || !data.access_token) {
        return new Response("OAuth error: " + (data.error_description || data.error || "unknown"), {
          status: 401,
        });
      }

      const payload = JSON.stringify({ token: data.access_token, provider: "github" });
      const html =
        "<!doctype html><html><head><meta charset='utf-8'></head><body><p>Logging you in…</p><script>" +
        "(function(){" +
        "function receive(e){" +
        "window.opener.postMessage('authorization:github:success:" + payload + "', e.origin);" +
        "window.removeEventListener('message', receive, false);" +
        "}" +
        "window.addEventListener('message', receive, false);" +
        "window.opener.postMessage('authorizing:github', '*');" +
        "})();" +
        "</script></body></html>";

      return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } });
    }

    return new Response("Not found", { status: 404 });
  },
};
