/**
 * The Candid Duo — CMS backend worker (Cloudflare Workers)
 * ---------------------------------------------------------
 * This tiny free service does three things for the hand-built CMS at /admin:
 *   1. Logs you in with your GitHub account (unchanged since the Decap days).
 *   2. Proxies "Generate with AI" story requests to the Gemini API.
 *   3. Proxies "Fetch details from URL" product-link lookups (also via
 *      Gemini) — fetching arbitrary product pages and extracting the image
 *      must happen server-side anyway (the browser can't do either due to
 *      CORS), so it rides the same Gemini key as AI stories.
 * Both AI features keep your API key server-side instead of in the
 * browser's JS where anyone could read it. Gemini was picked for these two
 * specifically because Google AI Studio's free tier needs no credit card —
 * unlike most other providers, this stays $0 for normal personal-blog use.
 * You do NOT edit this file's logic. Just copy ALL of it into the Cloudflare
 * Worker editor, then set the secrets below. Step-by-step instructions are
 * in SETUP-GUIDE.md (Step 6 for login, Step 6f for the AI features).
 *
 * Secrets to set in the Cloudflare dashboard (Settings → Variables and Secrets):
 *   GITHUB_CLIENT_ID      — from your GitHub OAuth App (Step 6b)
 *   GITHUB_CLIENT_SECRET  — from your GitHub OAuth App (Step 6b)
 *   GITHUB_REPO           — "YOURNAME/YOURNAME.github.io" — required for the
 *                           AI features, so only someone with push access to
 *                           *this* repo can trigger them
 *   GEMINI_API_KEY        — free, from aistudio.google.com/apikey — required
 *                           for the AI features only; login works without it
 */

const AI_MODEL = "gemini-2.0-flash";
const MAX_AI_IMAGES = 6;
const MAX_AI_DOCUMENTS = 3;
const MAX_FETCHED_IMAGE_BYTES = 8 * 1024 * 1024;

const AI_CORS_HEADERS = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "POST, OPTIONS",
  "access-control-allow-headers": "content-type, authorization",
};

// Both AI routes below count against the site owner's Gemini free-tier quota,
// so they require a real GitHub session with push access to *this* repo —
// otherwise anyone who found this worker's URL could burn through that quota
// with a throwaway GitHub account.
async function requirePushAccess(request, env) {
  if (!env.GEMINI_API_KEY) return { ok: false, status: 500, message: "Missing GEMINI_API_KEY secret" };
  if (!env.GITHUB_REPO) return { ok: false, status: 500, message: "Missing GITHUB_REPO secret" };

  const authHeader = request.headers.get("authorization") || "";
  const githubToken = authHeader.replace(/^Bearer\s+/i, "");
  if (!githubToken) return { ok: false, status: 401, message: "Missing GitHub session" };

  const repoRes = await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}`, {
    headers: {
      authorization: `Bearer ${githubToken}`,
      "user-agent": "candidduo-cms-ai-worker",
      accept: "application/vnd.github+json",
    },
  });
  if (!repoRes.ok) return { ok: false, status: 401, message: "Invalid GitHub session" };
  const repoData = await repoRes.json();
  if (!repoData.permissions || !repoData.permissions.push)
    return { ok: false, status: 403, message: "Not authorized for this site" };
  return { ok: true };
}

function guessPlatform(hostname) {
  const h = (hostname || "").toLowerCase();
  if (h.includes("shopee")) return "Shopee";
  if (h.includes("amazon") || h.includes("amzn")) return "Amazon";
  if (h.includes("lazada")) return "Lazada";
  if (h.includes("tiktok")) return "TikTok Shop";
  if (h.includes("etsy")) return "Etsy";
  return "Other";
}

const PRODUCT_SYSTEM_PROMPT =
  "You extract product info from an e-commerce page's raw HTML for a travel " +
  "blog's affiliate product CMS. Look at meta tags (og:title, og:image, " +
  'og:description, product:price:amount), JSON-LD <script type="application/ld+json"> ' +
  "Product schema, and any visible price/title text in the HTML. If the page " +
  'is a bot-block / CAPTCHA / "enable JavaScript" placeholder with no real ' +
  "product info, return empty strings for fields you can't find rather than " +
  "guessing. Respond with JSON matching the given schema only.";

// Gemini's structured-output schema format (note: uppercase type names —
// this is Google's own Schema type, not standard JSON Schema).
const PRODUCT_RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    name: { type: "STRING", description: "Product name/title. Empty string if not found." },
    price: { type: "STRING", description: "Price with currency as shown on the page, e.g. 'SGD 45.90'. Empty string if not found." },
    blurb: { type: "STRING", description: "One short sentence describing the product. Empty string if not found." },
    category: { type: "STRING", description: "A short category guess, e.g. 'Camera Gear', 'Travel Essentials'. Empty string if unsure." },
    image_url: { type: "STRING", description: "Best absolute product photo URL found (from og:image or similar). Empty string if not found." },
  },
  required: ["name", "price", "blurb", "category", "image_url"],
};

const AI_SYSTEM_PROMPT =
  'You are a travel writer for "The Candid Duo," a warm, first-person travel ' +
  "blog written by two friends who share honest, practical, occasionally " +
  "funny stories about their trips. Given a prompt from the site admin (and " +
  "any attached photos, PDFs, or notes), write a complete blog post in that " +
  "voice: personal, vivid, specific — real place names, food, small moments " +
  "— never generic listicle copy. Keep paragraphs short. Write the body in " +
  "Markdown. Respond with JSON matching the given schema only.";

const STORY_RESPONSE_SCHEMA = {
  type: "OBJECT",
  properties: {
    title: { type: "STRING", description: "Story title, under ~70 characters." },
    dek: { type: "STRING", description: "One italic subtitle line shown under the title." },
    excerpt: { type: "STRING", description: "1-2 sentence summary shown on cards and in search results." },
    tags: { type: "ARRAY", items: { type: "STRING" }, description: "3-6 short topical tags." },
    body: { type: "STRING", description: "Full story body in Markdown, several paragraphs." },
  },
  required: ["title", "dek", "excerpt", "tags", "body"],
};

// Calls Gemini's generateContent endpoint with structured-output enabled and
// returns the already-parsed JSON object, or throws with a message safe to
// show the CMS user.
async function callGemini(env, { systemPrompt, parts, schema }) {
  const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${AI_MODEL}:generateContent`, {
    method: "POST",
    headers: { "content-type": "application/json", "x-goog-api-key": env.GEMINI_API_KEY },
    body: JSON.stringify({
      contents: [{ role: "user", parts }],
      systemInstruction: { parts: [{ text: systemPrompt }] },
      generationConfig: { responseMimeType: "application/json", responseSchema: schema },
    }),
  });
  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error("AI request failed: " + errText);
  }
  const result = await res.json();
  const textPart = (result.candidates?.[0]?.content?.parts || []).find((p) => p.text)?.text;
  if (!textPart) throw new Error("AI did not return a structured result");
  try {
    return JSON.parse(textPart);
  } catch {
    throw new Error("AI returned invalid JSON");
  }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const { pathname, searchParams } = url;
    const origin = url.origin;
    const CLIENT_ID = env.GITHUB_CLIENT_ID;
    const CLIENT_SECRET = env.GITHUB_CLIENT_SECRET;

    // Health check
    if (pathname === "/") {
      return new Response("The Candid Duo — CMS auth worker is running ✓", {
        headers: { "content-type": "text/plain; charset=utf-8" },
      });
    }

    // AI story generation — called via fetch() from the CMS, so (unlike the
    // popup-based /auth and /callback above) it needs real CORS handling.
    if (pathname === "/generate-story") {
      const corsHeaders = AI_CORS_HEADERS;
      if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
      if (request.method !== "POST")
        return new Response("Method not allowed", { status: 405, headers: corsHeaders });

      const access = await requirePushAccess(request, env);
      if (!access.ok) return new Response(access.message, { status: access.status, headers: corsHeaders });

      let body;
      try {
        body = await request.json();
      } catch {
        return new Response("Invalid JSON body", { status: 400, headers: corsHeaders });
      }
      const { prompt, images = [], documents = [], notes = [] } = body || {};
      if (!prompt || typeof prompt !== "string")
        return new Response("Missing prompt", { status: 400, headers: corsHeaders });
      if (images.length > MAX_AI_IMAGES)
        return new Response(`Too many images (max ${MAX_AI_IMAGES})`, { status: 400, headers: corsHeaders });
      if (documents.length > MAX_AI_DOCUMENTS)
        return new Response(`Too many documents (max ${MAX_AI_DOCUMENTS})`, { status: 400, headers: corsHeaders });

      const parts = [];
      for (const img of images) {
        if (!img || !img.data) continue;
        parts.push({ inline_data: { mime_type: img.mediaType || "image/jpeg", data: img.data } });
      }
      for (const doc of documents) {
        if (!doc || !doc.data) continue;
        parts.push({ inline_data: { mime_type: "application/pdf", data: doc.data } });
      }
      for (const note of notes) {
        if (!note || !note.text) continue;
        parts.push({ text: `Reference file "${note.name || "notes"}":\n${note.text}` });
      }
      parts.push({ text: prompt });

      let story;
      try {
        story = await callGemini(env, { systemPrompt: AI_SYSTEM_PROMPT, parts, schema: STORY_RESPONSE_SCHEMA });
      } catch (e) {
        return new Response(e.message, { status: 502, headers: corsHeaders });
      }

      return new Response(JSON.stringify(story), {
        headers: { ...corsHeaders, "content-type": "application/json" },
      });
    }

    // "Fetch details from URL" on the Products editor — fetches the product
    // page server-side (the browser can't, due to CORS), asks Gemini to
    // pull out name/price/blurb/category/image from the raw HTML, and
    // best-effort downloads the image too so it can be re-uploaded to the
    // repo like any other CMS image instead of hot-linking someone else's URL.
    if (pathname === "/fetch-product") {
      const corsHeaders = AI_CORS_HEADERS;
      if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
      if (request.method !== "POST")
        return new Response("Method not allowed", { status: 405, headers: corsHeaders });

      const access = await requirePushAccess(request, env);
      if (!access.ok) return new Response(access.message, { status: access.status, headers: corsHeaders });

      let body;
      try {
        body = await request.json();
      } catch {
        return new Response("Invalid JSON body", { status: 400, headers: corsHeaders });
      }
      const productUrl = (body && body.url ? String(body.url) : "").trim();
      if (!productUrl) return new Response("Missing url", { status: 400, headers: corsHeaders });
      let parsed;
      try {
        parsed = new URL(productUrl);
      } catch {
        return new Response("That doesn't look like a valid URL", { status: 400, headers: corsHeaders });
      }
      if (parsed.protocol !== "http:" && parsed.protocol !== "https:")
        return new Response("That doesn't look like a valid URL", { status: 400, headers: corsHeaders });

      const platform = guessPlatform(parsed.hostname);
      const browserHeaders = {
        "user-agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
      };

      let html = "";
      try {
        const pageRes = await fetch(productUrl, {
          headers: { ...browserHeaders, accept: "text/html,application/xhtml+xml" },
          redirect: "follow",
        });
        if (pageRes.ok) html = (await pageRes.text()).slice(0, 120000);
      } catch {
        // Best-effort: some sites block server-side fetches entirely. Fall
        // through with an empty page and let the client know nothing came back.
      }

      let extracted = null;
      if (html) {
        try {
          extracted = await callGemini(env, {
            systemPrompt: PRODUCT_SYSTEM_PROMPT,
            parts: [{ text: `Page URL: ${productUrl}\n\nPage HTML (truncated):\n${html}` }],
            schema: PRODUCT_RESPONSE_SCHEMA,
          });
        } catch {
          // Leave extracted as null; the client still gets the platform guess.
        }
      }

      let image = null;
      if (extracted && extracted.image_url) {
        try {
          const imgRes = await fetch(extracted.image_url, { headers: browserHeaders });
          if (imgRes.ok) {
            const buf = await imgRes.arrayBuffer();
            if (buf.byteLength > 0 && buf.byteLength <= MAX_FETCHED_IMAGE_BYTES) {
              const bytes = new Uint8Array(buf);
              let binary = "";
              for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
              image = { data: btoa(binary), mediaType: imgRes.headers.get("content-type") || "image/jpeg" };
            }
          }
        } catch {
          // Fall back to returning just the image URL below.
        }
      }

      return new Response(
        JSON.stringify({
          platform,
          name: extracted?.name || "",
          price: extracted?.price || "",
          blurb: extracted?.blurb || "",
          category: extracted?.category || "",
          imageUrl: extracted?.image_url || "",
          image,
          pageFetched: Boolean(html),
        }),
        { headers: { ...corsHeaders, "content-type": "application/json" } }
      );
    }

    // 1) Kick off GitHub login
    if (pathname === "/auth") {
      if (!CLIENT_ID) return new Response("Missing GITHUB_CLIENT_ID secret", { status: 500 });
      const gh = new URL("https://github.com/login/oauth/authorize");
      gh.searchParams.set("client_id", CLIENT_ID);
      gh.searchParams.set("redirect_uri", `${origin}/callback`);
      gh.searchParams.set("scope", searchParams.get("scope") || "repo,user");
      gh.searchParams.set("state", crypto.randomUUID());
      return Response.redirect(gh.toString(), 302);
    }

    // 2) GitHub sends the user back here with a code
    if (pathname === "/callback") {
      const code = searchParams.get("code");
      if (!code) return new Response("Missing ?code", { status: 400 });
      if (!CLIENT_ID || !CLIENT_SECRET)
        return new Response("Missing GitHub client secrets", { status: 500 });

      const tokenRes = await fetch("https://github.com/login/oauth/access_token", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          accept: "application/json",
          "user-agent": "decap-cms-oauth-worker",
        },
        body: JSON.stringify({ client_id: CLIENT_ID, client_secret: CLIENT_SECRET, code }),
      });
      const data = await tokenRes.json();

      if (data.error || !data.access_token) {
        return new Response("OAuth error: " + (data.error_description || data.error || "unknown"), {
          status: 401,
        });
      }

      const payload = JSON.stringify({ token: data.access_token, provider: "github" });
      const html =
        "<!doctype html><html><head><meta charset='utf-8'></head><body><p>Logging you in…</p><script>" +
        "(function(){" +
        "function receive(e){" +
        "window.opener.postMessage('authorization:github:success:" + payload + "', e.origin);" +
        "window.removeEventListener('message', receive, false);" +
        "}" +
        "window.addEventListener('message', receive, false);" +
        "window.opener.postMessage('authorizing:github', '*');" +
        "})();" +
        "</script></body></html>";

      return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } });
    }

    return new Response("Not found", { status: 404 });
  },
};
