// Writes ../lib/THIRD-PARTY-LICENSES.txt: the license text of every package that
// is bundled into ../lib/editor.bundle.js (the production dependency tree only).
// Runs as part of `npm run build`, so the notices always match the bundle.
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const paths = execSync("npm ls --omit=dev --all --parseable --long=false", { encoding: "utf8" })
  .split("\n")
  .map((s) => s.trim())
  .filter((p) => p && p !== process.cwd() && fs.existsSync(path.join(p, "package.json")));

const seen = new Set();
const blocks = [];
for (const dir of paths) {
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  const id = `${pkg.name}@${pkg.version}`;
  if (seen.has(id)) continue;
  seen.add(id);
  const file = fs.readdirSync(dir).find((f) => /^(licen[sc]e|copying)(\.|$)/i.test(f));
  const text = file ? fs.readFileSync(path.join(dir, file), "utf8").trim() : `(no license file shipped; package.json declares: ${pkg.license || "unknown"})`;
  blocks.push({ id, license: typeof pkg.license === "string" ? pkg.license : JSON.stringify(pkg.license), text });
}
blocks.sort((a, b) => a.id.localeCompare(b.id));

const out =
  "Third-party software bundled into editor.bundle.js (the CMS visual editor).\n" +
  "Generated by admin/editor-src/licenses.mjs — do not edit by hand.\n\n" +
  blocks.map((b) => `${"=".repeat(72)}\n${b.id}  —  ${b.license}\n${"=".repeat(72)}\n${b.text}\n`).join("\n");
fs.writeFileSync(path.resolve("../lib/THIRD-PARTY-LICENSES.txt"), out);
console.log(`licenses: ${blocks.length} packages -> ../lib/THIRD-PARTY-LICENSES.txt`);
